export const DEFAULT_CATEGORIES = [
  { id: 1, name: 'Shopping', icon: 'shopping-cart', color: '#2979FF' },
  { id: 2, name: 'Internet', icon: 'wifi', color: '#FF9800' },
  { id: 3, name: 'Cleaning', icon: 'check-circle', color: '#00BCD4' },
  { id: 4, name: 'Rent', icon: 'home', color: '#673AB7' },
  { id: 5, name: 'Settlement', icon: 'dollar-sign', color: '#10B981' },
  { id: 6, name: 'Other', icon: 'plus', color: '#E91E63' },
  { id: 7, name: 'Food', icon: 'coffee', color: "#FF5722" },
  { id: 8, name: 'Transportation', icon: 'truck', color: '#9C27B0' },
  { id: 9, name: 'Health', icon: 'heart', color: '#F44336' },
  { id: 10, name: 'Entertainment', icon: 'film', color: '#3F51B5' },
  { id: 12, name: 'Education', icon: 'book', color: '#4CAF50' },
  { id: 13, name: 'Bills', icon: 'file-text', color: '#FFC107' },
  { id: 14, name: 'Groceries', icon: 'shopping-bag', color: '#8BC34A' },
  { id: 15, name: 'Utilities', icon: 'zap', color: '#FF9800' },
  { id: 16, name: 'Clothing', icon: 'tag', color: '#E91E63' },
  { id: 17, name: 'Gifts', icon: 'gift', color: '#9C27B0' },
  { id: 19, name: 'Pets', icon: 'heart', color: '#FF5722' },
  { id: 20, name: 'Subscriptions', icon: 'repeat', color: '#3F51B5' },
  { id: 22, name: 'Sports', icon: 'activity', color: '#4CAF50' },
  { id: 23, name: 'Hobbies', icon: 'smile', color: '#FFC107' },
  { id: 24, name: 'Taxes', icon: 'file-text', color: '#8BC34A' },
  { id: 25, name: 'Gadgets', icon: 'smartphone', color: '#00BCD4' },
  { id: 26, name: 'Furniture', icon: 'home', color: '#FF9800' },
  { id: 28, name: 'Car', icon: 'truck', color: '#9C27B0' },
  { id: 29, name: 'Fuel', icon: 'droplet', color: '#03A9F4' },
  { id: 31, name: 'Parking', icon: 'map-pin', color: '#3F51B5' },
  { id: 35, name: 'Hotel', icon: 'home', color: '#00BCD4' },
  { id: 36, name: 'Books', icon: 'book', color: '#FF9800' },
  { id: 37, name: 'Courses', icon: 'book-open', color: '#E91E63' },
  { id: 38, name: 'Music', icon: 'music', color: '#9C27B0' },
  { id: 39, name: 'Movies', icon: 'film', color: '#03A9F4' },
  /* { id: 40, name: 'Games', icon: 'game-controller', color: '#FF5722' }, */
];
